Repository fosslight-oss/if-you-are-rich-then-do-not-solve-algorithm, pull requests merged in 2023-11, with the labels that each got.

#89 [231101] feat: solve 프로그래머스 - 이진 변환 반복하기
  hello70825/programmers_70129.py
Labels: 프로그래머스

#90 [231101] feat: solve programmers 점프와순간이동
  dener8/programmers_점프와순간이동.py
Labels: 프로그래머스

#91 [231101] feat: solve 프로그래머스 - 피로도
  d0ri123/Programmers25.java
Labels: 프로그래머스

#93 [231101] feat: solve BOJ 11000 강의실배정
  jiwon83/BOJ_11000_강의실배정.java
Labels: 백준

#92 [231101] feat: solve 프로그래머스 시소 짝꿍
  suheoon/pg_23.cpp
Labels: 프로그래머스

#95 [231102] feat: solve BOJ_11279_최대힙
  jiwon83/BOJ_11279_최대힙.java
Labels: 백준

#94 [231102] feat: solve 프로그래머스 - 쿼드압축 후 개수 세기
  hello70825/programmers_68936.py
Labels: 프로그래머스

#96 [231102] feat: solve programmers 예상대진표
  dener8/programmers_예상대진표.py
Labels: 프로그래머스

#97 [231102] feat: sovle 프로그래머스 틱 택 토
  suheoon/pg_24.cpp
Labels: 프로그래머스

#98 [231103] feat: solve 프로그래머스 - 카펫
  d0ri123/Programmers26.java
Labels: 프로그래머스

#100 [231103] feat: solve 프로그래머스 호텔 대실
  suheoon/pg_25.cpp
Labels: 프로그래머스

#101 [231103] feat: solve programmers 의상
  dener8/programmers_의상.py
Labels: 프로그래머스

#102 [231104] feat: solve 프로그래머스 숫자변환
  suheoon/pg_26.cpp
Labels: 프로그래머스

#104 [231104] feat: solve 프로그래머스 - H-index
  hello70825/programmers_42747.py
Labels: 프로그래머스

#105 [231104] feat: solve programmers 올바른괄호
  dener8/programmers_올바른괄호.py
Labels: 프로그래머스

#106 [231104] feat: solve 프록래머스 - 과제 진행하기
  d0ri123/Programmers28.java
Labels: 프로그래머스

#107 [231105] feat: solve 인프런_겹쳐진압축해제
  jiwon83/인프런_겹쳐진압축해제.java
Labels: etc

#108 [231105] feat: solve 프로그래머스 짝지어 제거하기
  suheoon/pg_27.cpp
Labels: 프로그래머스

#109 [231105] feat: solve programmers JadenCase문자열만들기
  dener8/programmers_JadenCase문자열만들기.py
Labels: 프로그래머스

#112 [231106] feat: solve 프로그래머스 - 소수 찾기
  d0ri123/Programmers29.java
Labels: 프로그래머스

#113 [231106] feat: sovle 프로그래머스 카펫
  suheoon/pg_28.cpp
Labels: 프로그래머스

#114 [231106] feat: solve 프로그래머스 - 최솟값 만들기
  hello70825/programmers_12941.py
Labels: 프로그래머스

#116 [231106] feat: solve programmers 숫자의표현
  dener8/programmers_숫자의표현.py
Labels: 프로그래머스

#117 [231107] feat : solve BOJ 1744 수묶기
  jiwon83/BOJ_1744_수묶기.java
Labels: 백준

#115 [231107] feat: solve 프로그래머스 - 멀리 뛰기
  hello70825/programmers_12914.py
Labels: 프로그래머스

#118 [231107] feat: sovle 프로그래머스 거리두기
  suheoon/boj_29.cpp
Labels: 프로그래머스

#119 [231107] feat: solve programmers 뒤에있는큰수찾기
  dener8/programmers_뒤에있는큰수찾기.py
Labels: 프로그래머스

#120 [231107] feat: solve 프로그래머스 - 땅따먹기
  d0ri123/Programmers30.java
Labels: 프로그래머스

#122 [231108] feat: solve BOJ 동방프로젝트
  jiwon83/BOJ_14594_동방프로젝트.java
Labels: 백준

#123 [231108] feat: sovle 프로그래머스 튜플
  suheoon/pg_29.cpp
Labels: 프로그래머스

#121 [231108] feat: solve 프로그래머스 - 네트워크
  hello70825/programmers_43162.py
Labels: 프로그래머스

#124 [231108] feat: solve 프로그래머스 - 우박수열 정적분
  d0ri123/Programmers31.java
Labels: 프로그래머스

#125 [231108] feat: solve programmers 두큐합같게만들기
  dener8/programmers_두큐합같게만들기.py
Labels: 프로그래머스

#126 [231109] feat: solve programmers 신고결과받기
  dener8/programmers_신고결과받기.py
Labels: 프로그래머스

#129 [231110] feat: solve LeetCode 31 NextPermutation
  jiwon83/LeetCode_31_NextPermutation.java
Labels: 리트코드

#128 [231109] feat: solve 프로그래머스-광물캐기
  d0ri123/Programmers32.java
Labels: 프로그래머스

#130 [231109] feat: sovle 프로그래머스 폰번호
  suheoon/pg_30.cpp
Labels: 프로그래머스

#131 [231110] feat: solve programmers 주차요금계산
  dener8/programmers_주차요금계산.py
Labels: 프로그래머스

#132 [231110]feat: solve 프로그래머스 - 요격시스템
  d0ri123/Programmers33.java
Labels: 프로그래머스

#134 [231110] feat: solve BOJ 파일합치기
  jiwon83/BOJ_11066_파일합치기.java
Labels: 백준

#135 [231110] feat: solve 프로그래머스 - 야근 지수
  hello70825/programmers_12927.py
Labels: 프로그래머스

#133 [231110] feat: solve 프로그래머스 후보키
  suheoon/pg_31.cpp
  suheoon/pg_32.cpp
Labels: 프로그래머스

#136 [231111] feat: solve 프로그래머스 - 최고의 집합
  hello70825/programmers_12938.py
Labels: 프로그래머스

#137 [231111] feat: sovle 백준 비밀번호찾기
  suheoon/30454
  suheoon/30454.cpp
Labels: 백준

#138 [231111] feat: solve BOJ_9081_단어맞추기
  jiwon83/BOJ_9081_단어맞추기.java
Labels: 백준

#139 [231111] feat: solve programmers 정수삼각형
  dener8/programmers_정수삼각형.py
Labels: 프로그래머스

#140 [231112] feat: solve BOJ_1783_병든나이트
  jiwon83/BOJ_1783_병든나이트.java
Labels: 백준

#141 [231112] feat: solve 백준 소트인사이트
  suheoon/boj_1427.cpp
Labels: 백준

#142 [231112] feat : solve 프로그래머스 - 택배 배달과 수거하기
  d0ri123/Programmers34.java
Labels: 프로그래머스

#143 [231112] feat: solve 프로그래머스 - 단어 변환
  hello70825/programmers_43163.py
Labels: 프로그래머스

#144 [231112] feat: solve programmers k진수에서소수개수구하기
  dener8/programmers_k진수에서소수개수구하기.py
Labels: 프로그래머스

#145 [231113] feat: solve 프로그래머스 - 등굣길
  hello70825/programmers_42898.py
Labels: 프로그래머스

#148 [231113] feat: solve BOJ PPAP
  jiwon83/BOJ_16120_PPAP.java
Labels: 백준

#147 [231113] feat: solve BOJ 11008
  suheoon/boj_11008.cpp
Labels: 백준

#150 [231114] feat: solve BOJ 시그널
  jiwon83/BOJ_16113_시그널.java
Labels: 백준

#149 [231113] feat: solve programmers 할인행사
  dener8/programmers_할인행사.py
Labels: 프로그래머스

#153 [231114] feat: solve programmers 튜플
  dener8/programmers_튜플.py
Labels: 프로그래머스

#154 [231114] feat: solve 프로그래머스 - 최고의 집합
  d0ri123/Programmers36.java
Labels: 프로그래머스

#155 [231115] feat: solve BOJ 숫자의 합
  jiwon83/BOJ11720_숫자의합.java
Labels: 백준

#156 [231115] feat: solve 백준 성적 통계
  suheoon/boj_5800.cpp
Labels: 백준

#157 [231115] feat: solve 프로그래머스 - 징검다리 건너기
  d0ri123/Programmers37.java
Labels: 프로그래머스

#158 [231115] feat: solve programmers 연속부분수열합의개수
  dener8/programmers_연속부분수열합의개수.py
Labels: 프로그래머스

#159 [231115] feat: solve 프로그래머스 - 문자열 내림차순으로 배치하기
  hello70825/programmers_12917.py
Labels: 프로그래머스

#161 [231116] feat: solve 프로그래머스_추석트래픽
  jiwon83/프로그래머스_추석트래픽.java
Labels: 프로그래머스

#160 [231116] feat: solve 백준 중복빼고 정렬하기
  suheoon/boj_10867.cpp
Labels: 백준

#163 [231116] feat: solve programmers 괄호회전하기
  dener8/programmers_괄호회전하기.py
Labels: 프로그래머스

#164 [231117] feat: solve 백준 거북이
  suheoon/boj_2959.cpp
Labels: 백준

#166 [231117] feat: solve BOJ늑대와올바른단어
  jiwon83/BOJ_13022_늑대와올바른단어.java
Labels: 백준

#165 [231117] feat: solve 프로그래머스 - 풍선 터뜨리기
  d0ri123/Programmers38.java
  d0ri123/Programmers39.java
Labels: 프로그래머스

#168 [231118] feat solve BOJ 경고
  jiwon83/BOJ_3029_경고.java
Labels: 백준

#167 [231117] feat: solve programmers 개인정보수집유효기간
  dener8/programmers_개인정보수집유효기간.py
Labels: 프로그래머스

#169 [231118] feat: solve 백준 NN
  suheoon/boj_11944.cpp
Labels: 백준

#170 [231118] feat: solve 프로그래머스 - 다단계 칫솔 판매
  d0ri123/Programmers40.java
Labels: 프로그래머스

#171 [231118] feat: solve programmers 다리를지나는트럭
  dener8/programmers_다리를지나는트럭.py
Labels: 프로그래머스

#173 [231119]feat: sovle BOJ 밀비급일
  jiwon83/BOJ_11365_밀비 급일.java
Labels: 백준

#172 [231119] feat: solve 백준 주사위 네개
  suheoon/boj_2484.cpp
Labels: 백준

#174 [231119] feat: solve 프로그래머스 - 모두 0으로 만들기
  d0ri123/Programmers41.java
Labels: 프로그래머스

#175 [231119] feat: solve programmers [1차]캐시
  dener8/programmers_[1차]캐시.py
Labels: 프로그래머스

#176 [231120] feat: solve programmers 베스트앨범
  dener8/programmers_베스트앨범.py
Labels: 프로그래머스

#178 [231120] feat: solve BOJ 그룹단어체커
  jiwon83/BOJ_1316_그룹 단어 체커.java
Labels: 백준

#177 [231120] feat: solve 프로그래머스 - 카운트다운
  d0ri123/Programmers42.java
Labels: 프로그래머스

#180 [231121] feat: solve 프로그래머스 - 숫자 문자열과 영단어
  d0ri123/Programmers43.java
Labels: 프로그래머스

#182 [231121] feat: solve BOJ-파이프옮기기
  jiwon83/BOJ_17017_파이프옮기기.java
Labels: 백준

#181 [231121] feat: solve 백준 Yangjojang of The Year
  suheoon/boj_11557.cpp
Labels: 백준

#183 [231122] feat: solve 프로그래머스 - 카카오 인턴 기출 (2018 ~ 2020)
  hello70825/programmers_64061.py
  hello70825/programmers_64062.py
  hello70825/programmers_64063.py
  hello70825/programmers_64064.py
  hello70825/programmers_64065.py
  hello70825/programmers_67256.py
  hello70825/programmers_67257.py
  hello70825/programmers_67258.py
  hello70825/programmers_67259.py
Labels: 프로그래머스

#185 [231122] feat: solve boj if문좀대신써줘
  jiwon83/BOJ_19673_IF문 좀 대신 써줘.java
Labels: 백준

#184 [231122] feat: solve 백준 숫자카드
  suheoon/boj_10815.cpp
Labels: 백준

#186 [231122] feat: solve programmers 가장큰수
  dener8/programmers_가장큰수.py
Labels: 프로그래머스

#188 [231124] feat: solve BOJ 민균이의 비밀번호
  jiwon83/BOJ_9933_민균이의 비밀번호.java
Labels: 백준

#187 [231123] feat: solve 프로그래머스 - 직사각형 별찍기
  hello70825/programmers_12969.py
Labels: 프로그래머스

#189 [231123] feat: solve 백준 신입사원
  suheoon/boj_1946.cpp
Labels: 백준

#190 [231123] feat: solve programmers 숫자문자열과영단어
  dener8/programmers_숫자문자열과영단어.py
Labels: 프로그래머스

#192 [231124] feat : solve BOJ 로프
  jiwon83/BOJ_2217_로프.java
Labels: 백준

#191 [231124] feat: solve 프로그래머스 이모티콘 할인
  suheoon/pg_emoticon.cpp
Labels: 프로그래머스

#193 [231124] feat: solve 프로그래머스 - 숫자 문자열과 영단어
  hello70825/programmers_81301.py
Labels: 프로그래머스

#194 [231124] feat: solve programmers [1차]비밀지도
  dener8/programmers_[1차]비밀지도.py
Labels: 프로그래머스

#195 [231125] feat: solve 백준 0 = not cute / 1 = cute
  suheoon/boj_10886.cpp
Labels: 백준

#196 [231125]feat: solve BOJ 터렛
  jiwon83/BOJ_1002_터렛.java
Labels: 백준

#197 [231125] feat: solve programmers 과일장수
  dener8/programmers_과일장수.py
Labels: 프로그래머스

#198 [231126] feat: solve 백준 누울 자리를 찾아라
  suheoon/boj_1652.cpp
Labels: 백준

#199 [231126] feat: solve 프로그래머스 - 피타고라스의 정리
  hello70825/programmers_250132.py
Labels: 프로그래머스

#200 [231127] feat: solve 프로그래머스 - 프로세스
  hello70825/programmers_42587.py
Labels: 프로그래머스

#201 [231126] feat: solve programmers 두개뽑아서더하기
  dener8/programmers_두개뽑아서더하기.py
Labels: 프로그래머스

#202 [231126] feat: solve 프로그래모스 - 문제 풀이
  d0ri123/Programmers46.java
  d0ri123/Programmers47.java
Labels: 프로그래머스

#203 [231127] feat: solve BOJ 숫자재배치
  jiwon83/BOJ_16943_숫자 재배치.java
Labels: 백준

#207 [231128] feat: solve BOJ 마법사 상어와 파이어볼
  jiwon83/BOJ_20056_마법사 상어와 파이어볼.java
Labels: 백준

#205 [231127] feat: solve 프로그래머스 - 비밀지도
  d0ri123/Programmers44.java
Labels: 프로그래머스

#206 [231128] feat: solve 백준 R2
  suheoon/boj_3046.cpp
Labels: 백준

#208 [231128] feat: solve 프로그래머스 - 연속 펄스 부분 수열의 합
  d0ri123/Programmers45.java
Labels: 프로그래머스

#209 [231128] feat: solve programmers 2016년
  dener8/programmers_2016년.py
Labels: 프로그래머스

#210 [231129] feat: solve 백준 수들의 합
  suheoon/boj_1789.cpp
Labels: 백준

#211 [231128] feat: solve 프로그래머스 - 피보나치 수
  hello70825/programmers_12945.py
Labels: 프로그래머스

#212 [231129] feat: solve 프로그래머스 - 2xn 타일링
  hello70825/programmers_12900.py
Labels: 프로그래머스

#213 [231129] feat : solve 인프런 - 침몰하는 타이타닉
  jiwon83/인프런_침몰하는타이타닉.java
Labels: etc

#216 [231130] feat : solve 인프런 - 이동횟수
  jiwon83/인프런_이동횟수.java
Labels: etc

#215 [231129] feat: solve programmers 성격유형검사하기
  dener8/programmers_성격유형검사하기.py
Labels: 프로그래머스

#217 [231130] feat: solve 프로그래머스 - 요격시스템
  d0ri123/Programmers49.java
Labels: 프로그래머스

#218 [231130] feat: solve 프로그래머스 - 시저 암호
  hello70825/programmers_12926.py
Labels: 프로그래머스

#220 [231130] feat: solve programmers 삼총사
  dener8/programmers_삼총사.py
Labels: 프로그래머스

#219 [231201] feat: solve 프로그래머스 - 삼총사
  hello70825/programmers_131705.py
Labels: 프로그래머스

#222 [231201] feat: solve 인프런 스프링쿨러
  jiwon83/인프런_스프링쿨러.java
Labels: etc
