Repository fosslight-oss/if-you-are-rich-then-do-not-solve-algorithm, pull requests merged in 2023-12, with the labels that each got.

#224 [231201] feat: solve 백준 학점계산
  suheoon/boj_2754.cpp
Labels: 백준

#225 [231202] feat: solve 프로그래머스 - 정수 삼각형
  hello70825/programmers_43105.py
Labels: 프로그래머스

#226 [231201] feat: solve boj 8911 거북이
  dener8/boj_8911_거북이.py
Labels: 백준

#228 [231202] feat: solve 인프런 꽃피는시간
  jiwon83/인프런_꽃피는시간.java
Labels: etc

#227 [231202] feat: solve 백준 서울시간
  suheoon/boj_19699.cpp
Labels: 백준

#229 [231202] feat: solve 프로그래머스 - 카펫
  d0ri123/Programmers51.java
Labels: 프로그래머스

#232 [231203] feat: solve 인프런-전투게임
  jiwon83/인프런-전투게임.java
Labels: etc

#230 [231203] feat: solve 프로그래머스 - 숫자 게임
  hello70825/programmers_12987.py
Labels: 프로그래머스

#231 [231202] feat: solve boj 15686 치킨배달
  dener8/boj_15686_치킨배달.py
Labels: 백준

#237 [231204] feat: solve 프로그래머스 - 대충 만든 자판
  d0ri123/Programmers53.java
Labels: 프로그래머스

#239 [231204] feat: solve 프로그래머스 - 붕대 감기
  hello70825/programmers_250137.py
Labels: 프로그래머스

#240 [231205] feat: solve 프로그래머스 - 단속카메라
  hello70825/progrmaeers_42884.py
Labels: 프로그래머스

#241 [231204, 231205] solve 백준 인공지능시계, 저작권 풀이
  suheoon/boj_2530.cpp
  suheoon/boj_2914.cpp
Labels: 백준

#242 [231205] feat: solve BOJ 택배
  jiwon83/BOJ_8980_택배.java
Labels: 백준

#243 [231205] feat: solve 프로그래머스 - 비밀지도
  d0ri123/Programmers54.java
Labels: 프로그래머스

#244 [231205] feat: solve programmers 짝수와홀수
  dener8/programmers_짝수와홀수.py
Labels: 프로그래머스

#245 [231206] feat: solve boj 네번째 점
  suheoon/boj_3009.cpp
Labels: 백준

#246 [231206] feat: solve 프로그래머스 - 짝지어 제거하기
  hello70825/programmers_12973.py
Labels: 프로그래머스

#250 [231207] feat: solve BoJ 사탕가게
  jiwon83/BOJ_4781_사탕 가게.java
Labels: 백준

#248 [231206] feat: solve 프로그래머스 - 햄버거 만들기
  d0ri123/Programmers55.java
Labels: 프로그래머스

#252 [231207] feat: solve 프로그래머스 - 모의고사
  d0ri123/Programmers56.java
Labels: 프로그래머스

#253 [231207] feat: solve 프로그래머스 - 기능개발
  hello70825/programmers_42586.py
Labels: 프로그래머스

#254 [231208] feat: solve 프로그래머스 - 섬 연결하기
  hello70825/programmers_42861.py
Labels: 프로그래머스

#256 [231208] feat : solve BOJ 수도배관공사
  jiwon83/BOJ_2073_수도배관공사.java
Labels: 백준

#257 [231208] feat: solve programmers 시저암호
  dener8/programmers_시저암호.py
Labels: 프로그래머스

#258 [231208] feat: solve 프로그래머스 - 옹알이
  d0ri123/Programmers57.java
Labels: 프로그래머스

#260 [231209] feat: solve BOJ 크게만들기
  jiwon83/BOJ_2812_크게 만들기.java
Labels: 백준

#259 [231209] feat: solve BOJ 적어도 대부분의 배수
  suheoon/boj_1145.cpp
Labels: 백준

#263 [231209] feat: solve 프로그래머스 - 행렬의 덧셈
  hello70825/programmers_12950.py
Labels: 프로그래머스

#261 [231209] feat: solve 프로그래머스 - 최소 직사각형
  d0ri123/Programmers58.java
Labels: 프로그래머스

#262 [231209] feat: solve programmers 최고의집합
  dener8/programmers_최고의집합.py
Labels: 프로그래머스

#264 [231210] feat: solve BOJ 계단오르기
  jiwon83/BOJ_2579_계단 오르기.java
Labels: 백준

#265 [231210] feat: solve programmers 무인도여행
  dener8/programmers_무인도여행.py
Labels: 프로그래머스

#266 [231210] feat: solve BOJ 수 이야기
  suheoon/boj_2635.cpp
Labels: 백준

#267 [231210] feat: solve 프로그래머스 - 내적
  hello70825/programmers_70128.py
Labels: 프로그래머스

#269 [231211] feat: solve 인프런 이진수정렬
  jiwon83/인프런_이진수정렬.java
Labels: etc

#268 [231210] feat: solve 프로그래머스 - 의상
  d0ri123/Programmers59.java
Labels: 프로그래머스

#270 [231211] feat: solve boj 소수 & 펠린드롬
  suheoon/boj_1747.cpp
Labels: 백준

#271 [231211] feat: solve 프로그래머스 - 약수의 개수와 덧셈
  hello70825/programmers_77884.py
Labels: 프로그래머스

#273 [231212] feat: solve BOJ 등차수열
  jiwon83/BOJ_1994_등차수열.java
Labels: 백준

#272 [231211] feat: solve programmers 2xn타일링
  dener8/programmers_2xn타일링.py
Labels: 프로그래머스

#274 [231212] feat: solve boj 3190 뱀, programmers 택배상자
  dener8/boj_3190_뱀.py
  dener8/programmers_택배상자.py
Labels: 백준

#275 [231212] feat: solve 프로그래머스 - 문자열 다루기 기본
  hello70825/programmers_12918.py
Labels: 프로그래머스

#276 [231212] feat: solve boj 카드게임
  suheoon/boj_5522.cpp
Labels: 백준

#277 [231213] feat: solve BOJ 기차가 어둠을헤치고
  jiwon83/BOJ_15787_기차가 어둠을 헤치고 은하수를.java
Labels: 백준

#278 [231213] feat: solve 백준 등록
  suheoon/boj_7287.cpp
Labels: 백준

#279 [231213] feat: solve boj 2841 외계인의기타연주
  dener8/boj_2841_외계인의기타연주.py
Labels: 백준

#280 [231213] feat: solve 프로그래머스 - 같은 숫자는 싫어
  hello70825/programmers_12906.py
Labels: 프로그래머스

#281 [231214] feat: solve 프로그래머스 - 예산
  hello70825/programmers_12982.py
Labels: 프로그래머스

#283 [231214] feat: solve BOJ 줄어들지 않아
  jiwon83/BOJ_2688_줄어들지 않아.java
Labels: 백준

#282 [231214] feat: solve boj 21608 상어초등학교
  dener8/boj_21608_상어초등학교.py
Labels: 백준

#284 [231215] feat: solve 프로그래머스 - 최소직사각형
  hello70825/programmers_86491.py
Labels: 프로그래머스

#286 [231215] feat: solve 인프런 카드가져가기
  jiwon83/인프런_카드가져가기.java
Labels: etc

#285 [231215] feat: solve BOJ 평균점수
  suheoon/boj_10039.cpp
Labels: 백준

#287 [231215] feat: solve programmers 도둑질
  dener8/programmers_도둑질.py
Labels: 백준

#288 [231216] feat: solve 인프런 현관문 출입순서
  jiwon83/인프런_현관문출입순서.java
Labels: etc

#290 [231216] feat: solve 프로그래머스 - 푸드 파이트 대회
  hello70825/programmers_134240.py
Labels: 프로그래머스

#289 [231216] feat: solve programmers 2개이하로다른비트
  dener8/programmers_2개이하로다른비트.py
Labels: 프로그래머스

#291 [231217] feat: solve BOJ 마법사상어와 토네이도
  jiwon83/BOJ_20057_마법사 상어와 토네이도.java
Labels: 백준

#292 [231217] feat: solve 백준 연산
  suheoon/boj_53554.cpp
Labels: 백준

#293 [231218,231219] feat: solve 인프런 수열찾기, BOJ 16719 ZOAC
  jiwon83/BOJ_16719_ZOAC.java
  jiwon83/인프런_수열찾기.java
Labels: 백준

#294 [231217] feat: solve 프로그래머스 - 두 수의 곱
  hello70825/programmers_120804.py
Labels: 프로그래머스

#295 [231217] feat: solve programmers N으로표현
  dener8/programmers_N으로표현.py
Labels: 프로그래머스

#296 [231218] feat: solve softeer 순서대로방문하기
  dener8/softeer_순서대로방문하기.py
Labels: etc

#297 [231218] feat: solve 백준 과자
  suheoon/boj_10156.cpp
Labels: 백준

#298 [231218] feat: solve 프로그래머스 - 숫자 비교하기
  hello70825/programmers_120807.py
Labels: 프로그래머스

#299 [231219] feat: solve 프로그래머스 - 몫 구하기
  hello70825/programmers_120805.py
Labels: 프로그래머스

#300 [231219] feat: solve 백준 주사위 게임
  suheoon/boj_2476.cpp
Labels: 백준

#302 [231220] feat: solve BOJ 마법상어와 블리자드
  jiwon83/BOJ_21611_마법사 상어와 블리자드.java
Labels: 백준

#301 [231219] feat: solve boj 9655 돌게임
  dener8/boj_9655_돌게임.py
Labels: 백준

#303 [231220] feat: solve boj 1238 파티, programmers 가장먼노드
  dener8/boj_1238_파티.py
  dener8/programmers_가장먼노드.py
Labels: 백준, 프로그래머스

#304 [231220] feat: solve 백준 baseball
  suheoon/boj_10214.cpp
Labels: 백준

#305 [231220] feat: solve 프로그래머스 - 나이 출력
  hello70825/programmers_120820.py
Labels: 프로그래머스

#307 [231221] feat: solve boj 1261 알고스팟
  dener8/boj_1261_알고스팟.py
Labels: 백준

#308 [231222] feat: solve 프로그래머스 - 나머지 구하기
  hello70825/programmers_120810.py
Labels: 프로그래머스

#309 [231221] feat : solve BOJ22856 트리순회
  jiwon83/BOJ_22856_트리 순회.java
Labels: 백준

#310 [231222] feat: solve 인프런 - 피부과
  jiwon83/인프런_피부과.java
Labels: etc
