Repository fosslight-oss/if-you-are-rich-then-do-not-solve-algorithm, pull requests merged in 2023-10, with the labels that each got.

#1 [231013] feat: solve programmers 디스크 컨트롤러
  suheoon/pg_5.cpp
Labels: 프로그래머스

#2 [231013] solve 프로그래머스 의류
  d0ri123/Programmers06.java
Labels: 프로그래머스

#3 [231013] feat: solve programmers 네트워크
  dener8/programmers_네트워크.py
Labels: 프로그래머스

#4 [231013] feat: solve 프로그래머스 - 피로도
  hello70825/programmers_87946.py
Labels: 프로그래머스

#5 [231014] feat: solve programmers prirority queue
  suheoon/pg_6.cpp
Labels: 프로그래머스

#6 [231014] feat: solve 프로그래머스 - 뒤에 있는 큰 수 찾기, 디펜스 게임, 귤 고르기
  hello70825/programmers_138476.py
  hello70825/programmers_142085.py
  hello70825/programmers_154539.py
Labels: 프로그래머스

#7 [231014] feat: BOJ_1543_문서검색
  jiwon83/BOJ_1543_문서검색.java
  jiwon83/BOJ_2661_좋은수열.java
Labels: 백준

#8 [231014] feat: solve 프로그래머스 k번째 수
  d0ri123/Programmers07.java
Labels: 프로그래머스

#9 [231014] feat: solve programmers 귤고르기
  dener8/programmers_귤고르기.py
Labels: 프로그래머스

#10 [231015] feat: solve programmers clothes
  suheoon/pg_7.cpp
Labels: 프로그래머스

#11 [231015] feat: solve 프로그래머스 가장 큰 수
  d0ri123/Programmers08.java
Labels: 프로그래머스

#12 [231015] feat: solve programmers 멀리뛰기
  dener8/programmers_멀리뛰기.py
Labels: 프로그래머스

#13 [231015] feat: solve 프로그래머스 - 테이블 해시 함수
  hello70825/programmers_147354.py
Labels: 프로그래머스

#14 [231015] feat: BOJ 1259 팰린드롬수
  jiwon83/BOJ_1259_팰린드롬수.java
Labels: 백준

#15 [231016] feat: solve 프로그래머스 - 롤케이크 자르기
  hello70825/programmers_132265.py
Labels: 프로그래머스

#16 [231016] feat: solve 프로그래머스 카펫
  d0ri123/Programmers09.java
Labels: 프로그래머스

#17 [231016] feat: solve programmers 숫자변환하기
  dener8/programmers_숫자변환하기.py
Labels: 프로그래머스

#18 [231016] feat: solve programmers entry
  suheoon/pg_8.cpp
Labels: 프로그래머스

#20 [231017] feat: solve 프로그래머스 체육복
  d0ri123/Programmers10.java
Labels: 프로그래머스

#21 [231017] feat: solve 프로그래머스 - 숫자 카드 나누기, 택배상자
  hello70825/programmers_131704.py
  hello70825/programmers_135807.py
Labels: 프로그래머스

#24 [231017] feat: solve boj_1655
  suheoon/boj_1655.cpp
Labels: 백준

#25 [231018] feat: solve 프로그래머스 - 연속 부분 수열 합의 개수
  hello70825/programmers_131701.py
Labels: 프로그래머스

#26 [231018] feat: solve programmers 행렬의곱셈
  dener8/programmers_행렬의곱셈.py
Labels: 프로그래머스

#28 [231018] feat: solve 프로그래머스 오픈채팅방
  suheoon/pg_9.cpp
Labels: 프로그래머스

#30 [231019] feat: solve 프로그래머스 - 같은 숫자는 싫어
  d0ri123/Programmers12.java
  d0ri123/Programmers13.java
Labels: 프로그래머스

#31 [231019] feat: solve programmers 프로세스, 두원사이의정수쌍
  dener8/programmers_두원사이의정수쌍.py
  dener8/programmers_프로세스.py
Labels: 프로그래머스

#32 [231019] feat: solve 문자열압축
  suheoon/pg_10.cpp
Labels: 프로그래머스

#33 [231019] feat: solve BOJ - 이상한 아리의 채점
  hello70825/BOJ_25167.py
Labels: 백준

#34 [231020] feat: solve 프로그래머스 - 더 맵게
  d0ri123/Programmers14.java
Labels: 프로그래머스

#35 [231020] feat: solve programmers 모음사전
  dener8/programmers_모음사전.py
Labels: 프로그래머스

#36 [231020] feat: sovle 프로그래머스 모음사전
  suheoon/pg_11.cpp
Labels: 프로그래머스

#37 [231020] feat: solve 프로그래머스 - 할인 행사, n^2 배열 자르기
  hello70825/programmers_131127.py
  hello70825/programmers_87390.py
Labels: 프로그래머스

#40 [231021] feat: sovle 프로그래머스 수식 최대화
  suheoon/pg_12.cpp
Labels: 프로그래머스

#41 [231021] feat: solve 프로그래머스 - 기능 개발
  d0ri123/Programmers15.java
Labels: 프로그래머스

#42 [231021] feat: solve programmers 이중우선순위큐
  dener8/programmers_이중우선순위큐.py
Labels: 프로그래머스

#43 [231022] feat: sovle 프로그래머스 공원산책
  suheoon/pg_13.cpp
Labels: 프로그래머스

#45 [231022] feat : BOJ 2589 보물섬
  jiwon83/BOJ_2589_보물섬.java
Labels: 백준

#44 [231022] feat: solve 프로그래머스 - 괄호 회전하기
  hello70825/programmers_76502.py
Labels: 프로그래머스

#46 [231022] feat: solve programmers 이진변환반복하기
  dener8/programmers_이진변환반복하기.py
Labels: 프로그래머스

#47 [231022] feat: solve 프로그래머스 - 모음사전
  d0ri123/Programmers16.java
Labels: 프로그래머스

#48 [231023] feat: solve 프로그래머스 마법의 엘리베이터
  pg_14.cpp
Labels: 프로그래머스

#50 [231023] feat: BOJ 12908 텔레포트3
  jiwon83/BOJ_12908_텔레포트3.java
Labels: 백준

#51 [231023] feat: solve programmers 전화번호목록
  dener8/programmers_전화번호목록.py
Labels: 프로그래머스

#52 [231024] feat: solve 프로그래머스 무인도여행
  pg_15.cpp
Labels: 프로그래머스

#54 [231024] feat: solve 프로그래머스 - 디스크 컨트롤러
  d0ri123/Programmers18.java
Labels: 프로그래머스

#55 [231024] feat: solve programmers 스킬트리
  dener8/programmers_스킬트리.py
Labels: 프로그래머스

#57 [231025] feat: solve programmers 단어변환
  dener8/programmers_단어변환.py
Labels: 프로그래머스

#58 [231025] feat: solve 프로그래머스 - MySQL LV.4 ~ LV.5
  hello70825/programmers_131116.sql
  hello70825/programmers_131117.sql
  hello70825/programmers_131118.sql
  hello70825/programmers_131124.sql
  hello70825/programmers_131532.sql
  hello70825/programmers_131534.sql
  hello70825/programmers_131537.sql
  hello70825/programmers_132204.sql
  hello70825/programmers_133027.sql
  hello70825/programmers_144856.sql
  hello70825/programmers_151141.sql
  hello70825/programmers_157339.sql
  hello70825/programmers_59045.sql
  hello70825/programmers_59413.sql
  hello70825/programmers_62284.sql
Labels: 프로그래머스

#59 [231025] feat: solve 프로그래머스 - 조이스틱
  d0ri123/Programmers19.java
Labels: 프로그래머스

#61 [231025] feat: 인프런 같은빈도수만들기
  jiwon83/인프런_같은빈도수만들기.java
Labels: etc

#60 [231025] feat: solve 프로그래머스 약수의 개수와 덧셈
  suheoon/pg_14.cpp
  suheoon/pg_15.cpp
  suheoon/pg_16.cpp
Labels: 프로그래머스

#62 [231026] feat: solve 프로그래머스 두 큐 합 같게 만들기
  pg_14.cpp
  pg_15.cpp
  suheoon/pg_17.cpp
Labels: 프로그래머스

#63 [231026] feat: solve programmers 점찍기
  dener8/programmers_점찍기.py
Labels: 프로그래머스

#66 [231026] feat: solve 인프런 서로 다른 빈도수 만들기
  jiwon83/인프런_서로다른빈도수만들기.java
Labels: etc

#65 [231026] feat: solve 프로그래머스 - 타겟 넘버
  d0ri123/Programmers20.java
Labels: 프로그래머스

#67 [231027] feat: solve programmers 거리두기확인하기
  dener8/programmers_거리두기확인하기.py
Labels: 프로그래머스

#69 [231027] feat : solve 인프런_음수가있는부분수열
  jiwon83/인프런_음수가있는부분수열.java
Labels: etc

#68 [231027] feat: solve 프로그래머스 순위검색
  suheoon/pg_18.cpp
Labels: 프로그래머스

#70 [231027] feat: solve 프로그래머스 - 가운데 글자 가져오기
  hello70825/programmers_12903.java
Labels: 프로그래머스

#71 [231028] feat: solve 프로그래머스 JadenCase 문자열 만들기
  suheoon/pg_19.cpp
Labels: 프로그래머스

#72 [231028] feat: solve 프로그래머스 - 섬 연결하기
  d0ri123/Programmers21.java
Labels: 프로그래머스

#74 [231028] feat: solve 인프런 회장선거
  jiwon83/인프런_회장선거.java
Labels: etc

#73 [231028] feat: solve programmers 피보나치수
  dener8/programmers_피보나치수.py
Labels: 프로그래머스

#76 [231029] feat: solve 프로그래머스 성격 유형 검사하기
  suheoon/pg_20.cpp
Labels: 프로그래머스

#77 [231029] feat: solve programmers 짝지어제거하기
  dener8/programmers_짝지어제거하기.py
Labels: 프로그래머스

#78 [231029] feat: solve 프로그래머스 - 테스트 환경 문제, 무인도 여행
  hello70825/programmers_154540.java
  hello70825/programmers_test1.java
  hello70825/programmers_test2.java
  hello70825/programmers_test3.java
  hello70825/programmers_test4.sql
Labels: 프로그래머스

#79 [231029] feat: solve 프로그래머스 - 네트워크
  d0ri123/Programmers22.java
Labels: 프로그래머스

#82 [231030] feat : solve 인프런 경고메일
  jiwon83/인프런_경고메일.java
Labels: etc

#83 [231030] feat: solve 프로그래머스 - 단속 카메라
  d0ri123/Programmers23.java
Labels: 프로그래머스

#84 [231031] feat: solve programmers 다음큰숫자
  dener8/programmers_다음큰숫자.py
Labels: 프로그래머스

#86 [231031] feat: 프로그래머스 괄호 회전하기
  suheoon/pg_22.cpp
Labels: 프로그래머스

#87 [231031] feat: solve 프로그래머스 - 전력망을 둘로 나누기
  hello70825/programmers_86971.py
Labels: 프로그래머스

#88 [231031] feat: solve 프로그래머스 - 체육복
  d0ri123/Programmers10.java
  d0ri123/Programmers24.java
Labels: 프로그래머스
