Repository fosslight-oss/if-you-are-rich-then-do-not-solve-algorithm, pull requests merged in 2024-01, with the labels that each got.

#312 [230102] feat: solve 인프런 바둑대회
  jiwon83/인프런_바둑대회.java
Labels: etc

#311 [231222] feat: solve programmers 야근지수
  dener8/programmers_야근지수.py
Labels: 프로그래머스

#314 [240102] feat: solve 프로그래머스 - 콜라 문제
  hello70825/programmers_132267.py
Labels: 프로그래머스

#316 [240103] feat: solve boj 1890 점프
  dener8/boj_1890_점프.py
Labels: 백준

#317 [240103] feat: solve BOJ 12933 오리
  jiwon83/BOJ_12933_오리.java.txt
Labels: 백준

#320 [240103] feat: solve boj 16236 아기상어
  dener8/boj_16236_아기상어.py
Labels: 백준

#322 [240104] feat: solve boj 16236 아기상어
  dener8/boj_16236_아기상어.py
Labels: 백준

#323 [240105] feat : solve 백준9012 괄호
  jiwon83/BOJ_9012_괄호.java
Labels: 백준

#325 [240105] feat: solve BOJ 17298 오큰수
  jiwon83/BOJ_17298_오큰수.java.txt
Labels: 백준

#326 [240105] feat: solve boj 20056 마법사상어와파이어볼
  dener8/boj_20056_마법사상어와파이어볼.py
Labels: 백준

#327 [240105] feat: solve 프로그래머스 - 문자열 내 마음대로 정렬하기
  hello70825/programmers_12915.py
Labels: 프로그래머스

#329 [240107] feat: solve 인프런 가장많이사용된회의실
  jiwon83/인프런_가장많이사용된회의실.java
Labels: etc

#330 [240107] feat: solve boj 2504 괄호의값
  jiwon83/BOJ_2504_괄호의값.java
Labels: 백준

#332 [240108] feat: solve boj 1916 최소비용구하기
  dener8/boj_1916_최소비용구하기.py
Labels: 백준

#334 [240108] feat: solve 프로그래머스 - 더 맵게
  hello70825/programmers_42626.py
Labels: 프로그래머스

#335 [240109] feat: solve programmers 124나라의숫자
  dener8/programmers_124나라의숫자.py
Labels: 프로그래머스

#336 [240110] feat: solve BOJ 1935 후위표기식2
  jiwon83/BOJ_1935_후위표기식2.java
Labels: 백준

#338 [240110] feat: solve boj 6198 옥상정원꾸미기
  dener8/boj_6198_옥상정원꾸미기.py
Labels: 백준

#340 [240111] feat: solve boj 20040 사이클게임
  dener8/boj_20040_사이클게임.py
Labels: 백준

#341 [240111] feat: solve BOJ 1863 스카이라인쉬운거
  jiwon83/BOJ_1863_스카이라인쉬운거.java
Labels: 백준

#343 [240112] feat: solve boj 6497 전력난
  dener8/boj_6497_전력난.py
Labels: 백준

#344 [240112] feat: solve BOJ 21277 짠돌이 호석
  jiwon83/BOJ_21277_짠돌이 호석.java
Labels: 백준

#347 [240116] feat: solve BOJ22866 탑보기
  jiwon83/BOJ_22866_탑보기.java
Labels: 백준

#348 [240115] feat: solve boj 2056 작업
  dener8/boj_2056_작업.py
Labels: 백준

#349 [240115] feat: solve 프로그래머스 - 각도기
  hello70825/programmers_120829.py
Labels: 프로그래머스

#352 [240116] feat: solve boj 2252 줄세우기
  dener8/boj_2252_줄세우기.py
Labels: 백준

#353 [240117] feat :solve BOJ 4358 생태학
  jiwon83/BOJ_4358_생태학.java
Labels: 백준

#355 [240116] feat: solve 프로그래머스 - 짝수의 합
  hello70825/programmers_120831.py
Labels: 프로그래머스

#356 [240117] feat: solve 프로그래머스 - 두 수의 합
  hello70825/programmers_120802.py
Labels: 프로그래머스

#357 [240117] feat: solve programmers 소수만들기
  dener8/programmers_소수만들기.py
Labels: 프로그래머스

#359 [240118] feat : solve 인프런 cpu 스케줄링
  jiwon83/인프런_cpu스케줄링.java
Labels: etc

#361 [240118] feat: solve 프로그래머스 - 두 수의 나눗셈
  hello70825/programmers_120806.py
Labels: 프로그래머스

#362 [240119] feat: solve 프로그래머스 - 배열의 평균값
  hello70825/programmers_120817.py
Labels: 프로그래머스

#364 [240119] feat: solve programmers 기사단원의무기
  dener8/programmers_기사단원의무기.py
  dener8/programmers_추억점수.py
Labels: 프로그래머스

#366 [240122] feat: solve programmers 문자열내마음대로정렬하기
  dener8/programmers_문자열내마음대로정렬하기.py
Labels: 프로그래머스

#369 [240122] feat: solve 프로그래머스 - 문자열의 앞의 n글자
  hello70825/programmers_181907.py
Labels: 프로그래머스

#372 [240123] feat : solve BOJ 4781 사탕가게
  jiwon83/BOJ_4781_사탕가게.java
Labels: 백준

#373 [240123] feat: solve 프로그래머스 - 편지
  hello70825/programmers_120898.py
Labels: 프로그래머스

#374 [240124] feat: solve 프로그래머스 - 양꼬치
  hello70825/programmers_120830.py
Labels: 프로그래머스

#377 [240124] feat:solve BOJ 1106 호텔
  jiwon83/BOJ_1106_호텔.java
Labels: 백준

#378 [240125] feat: solve boj 11725 트리의부모찾기
  dener8/boj_11725_트리의부모찾기.py
Labels: 백준

#380 [240125] feat: solve 프로그래머스 - 배열 뒤집기
  hello70825/programmers_120821.py
Labels: 프로그래머스

#381 [240125] feat: solve BOJ 2754 윤년
  jiwon83/BOJ_2753_윤년.java
Labels: 백준

#383 [240126] feat: solve programmers H-Index
  dener8/programmers_H-Index.py
Labels: 프로그래머스

#385 [240129] feat: solve programmers 전력망을둘로나누기
  dener8/programmers_전력망을둘로나누기.py
Labels: 프로그래머스

#391 [240130] feat: solve programmers 콜라문제
  dener8/programmers_콜라문제.py
Labels: 프로그래머스

#393 [240130] feat: solve 프로그래머스 - 머쓱이보다 키가 큰 사람
  hello70825/programmers_120585.py
Labels: 프로그래머스

#394 [240131] feat: solve 프로그래머스 - 피자 나눠 먹기(1)
  hello70825/programmers_120814.py
Labels: 프로그래머스

#396 [240131] feat: solve programmers 가장가까운같은글자
  dener8/programmers_가장가까운같은글자.py
Labels: 프로그래머스
